CREATE TABLE WEAPON
(
    ID   varchar(255) PRIMARY KEY NOT NULL,
    NAME varchar(255) NOT NULL
);

CREATE TABLE PLAYER (
    ID varchar(255) PRIMARY KEY,
    NAME varchar(255),
    WEAPON_ID varchar(255),
    FOREIGN KEY (WEAPON_ID) REFERENCES WEAPON(ID)
);

