name: Maven Package

on:
  release:
    types: [created]

jobs:

  build-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: 'true'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Check if it's a pre-release
        id: check_prerelease
        run: echo ::set-output name=is_prerelease::$(jq '.release.prerelease' $GITHUB_EVENT_PATH)

      - name: Build with Maven
        run: mvn -B -DskipTests package -P $(if [ "${{ steps.check_prerelease.outputs.is_prerelease }}" == "true" ]; then echo "development"; else echo "stable"; fi) --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests -P stable -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.token }}